const dick = [
    {
      Id: 'anksunamun_tqoe',
      Name: 'Anksunamun the Queen of Egypt',
      Description: '10 Lines, Free & Feature',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'lions_pride',
      Name: 'Lions Pride',
      Description: '5*4, 40 Lines, Free, Wilds',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 're_kill',
      Name: 'ReKill',
      Description: '5*4, 40 Lines, Free & Feature, WReels',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'northern_heat',
      Name: 'Northern Heat',
      Description: '5*4, 40 Lines, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'cancan_saloon',
      Name: 'CanCan Saloon',
      Description: '15 Lines, Free, Bonus, WReels',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'the_rite',
      Name: 'The Rite',
      Description: '5*4, 40 Lines, Free, Bonus',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'venetian_magic',
      Name: 'Venetian Magic',
      Description: '6*4, 50 Lines, Sailing Wilds',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'mermaids_bay',
      Name: "Mermaid's Bay",
      Description: '25 Lines, Wild Features, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'merlins_tower',
      Name: "Merlin's Tower",
      Description: '5*4, 40 Lines, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'purple_pills',
      Name: 'Purple Pills',
      Description: '10 Lines, 2 way pay, Respin',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'robin_of_loxley',
      Name: 'Robin of Loxley',
      Description: '20 Lines, Free, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'riot',
      Name: 'Riot',
      Description: "15 Lines, Risk'n'Buy, 3*Features",
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'bamboo_bear',
      Name: 'Bamboo Bear',
      Description: '243 Ways, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'blackjack_mg',
      Name: 'Black Jack',
      Description: 'BJ, Card Game, 3 Hands',
      SectionId: 'mascot',
      Type: 'casino',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'baccarat_mg',
      Name: 'Baccarat',
      Description: 'Card Games',
      SectionId: 'mascot',
      Type: 'casino',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'gemz_grow',
      Name: 'Gemz Grow',
      Description: '243-3125 ways, Free*5',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'red_horde',
      Name: 'Red Horde',
      Description: '15 Lines, Modifiers, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'wild_spirit',
      Name: 'Wild Spirit',
      Description: '5*4, 40 Lines, Free, Wilds',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'fruit_vegas',
      Name: 'Fruit Vegas',
      Description: '10 Lines, 2 way pay, Respin',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'gryphons_castle',
      Name: 'Gryphons Castle',
      Description: '20 Lines, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'amaterasu_keno',
      Name: 'Amaterasu Keno',
      Description: '20/80 Balls, Multipliers, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'hellsing',
      Name: "Hell'Sing",
      Description: '5*4, 40 Lines, 2*Free, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'the_tomb_det',
      Name: "The Tomb: Dragon Emperor's Treasure",
      Description: '10 Lines, Free & Feature, Respins',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { Bets: [Array], CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'legioner',
      Name: 'Legioner',
      Description: '25 Lines, Wild Features, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'bennys_the_biggest_game',
      Name: "Benny's the Biggest game",
      Description: '20 Lines, Free, Bonus',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'aloha_tiki_bar',
      Name: 'Aloha Tiki Bar',
      Description: '3600 ways, respins',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'merry_scary_christmas',
      Name: 'Merry Scary Christmas',
      Description: '10 Lines, Free, Features, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'prince_of_persia_tgop',
      Name: 'Prince of Persia: the gems of Persepolis',
      Description: '10 Lines, Free & Feature, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'the_myth',
      Name: 'the Myth',
      Description: '10 Lines, 4*Free, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'bastet_and_cats',
      Name: 'Bastet and Cats',
      Description: '40 Lines, Free, Avalanches, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'zeus_the_thunderer',
      Name: 'Zeus the Thunderer',
      Description: '20 Lines, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'fruits_of_luxor',
      Name: 'Fruits of Luxor',
      Description: '15 Lines, 2 way pay, Respin',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'twin_fruits_of_olympus',
      Name: 'Twin Fruits of Olympus',
      Description: '1024 Way, Twin Reel',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'queen_of_spades',
      Name: 'Queen of Spades',
      Description: '10 Lines, Free, Bonus, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: '3_corsairs',
      Name: '3 Corsairs',
      Description: '40 Lines, Bonus, Free, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'fruit_macau',
      Name: 'Fruit Macau',
      Description: '9 Lines, Free, Multipliers',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'fruit_monaco',
      Name: 'Fruit Monaco',
      Description: '15 Lines, Free, Wilds',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'book_of_amaterasu',
      Name: 'Book of Amaterasu',
      Description: '10 Lines, Free & Feature, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'fairytale_coven',
      Name: 'Fairytale Coven',
      Description: "15 Lines, Risk'n'Buy, 3*Features",
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'twin_fruits_of_santa',
      Name: 'Twin Fruits of Santa',
      Description: '1024 Way, Twin Reel',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'for_the_realm',
      Name: 'For The Realm',
      Description: "15 Lines, Risk'n'Buy, 3*Features",
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'primal_bet_rockways',
      Name: 'Primal bet Rockways',
      Description: '6*6 rockways, avalanche, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'dragons_nest',
      Name: "Dragon's Nest",
      Description: '10 Lines, Free, Features, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'pinup_dolls',
      Name: 'Pinup Dolls',
      Description: '15 Lines, Free, Bonus, WReels, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'the_evil_bet',
      Name: 'the Evil Bet',
      Description: '15 Lines, Modifiers, Free, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'cleopatras_gems_rockways',
      Name: "Cleopatra's Gems Rockways",
      Description: '6*6 rockways, avalanche, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'candy_crush',
      Name: 'Candy Crush',
      Description: '6*5 rockways, avalanche, Free, features, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'across_the_universe',
      Name: 'Across the Universe',
      Description: '20 Lines, Free, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'holdem_mg',
      Name: "Casino Hold'em",
      Description: 'Card Games',
      SectionId: 'mascot',
      Type: 'casino',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'mayan_riches_rockways',
      Name: 'Mayan Riches Rockways',
      Description: '6*6 rockways, avalanche, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'riot_2_bnb',
      Name: 'Riot 2: Blow & Burn',
      Description: "50 Lines, Free, Risk'n'Buy, 2*Features",
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'fruit_disco_ms',
      Name: 'FRUIT DISCO: MEGA STACKS',
      Description: '20 lines, Twin Reel',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'double_triple_fruits',
      Name: 'Double Triple Fruits',
      Description: '5*3, 15 Lines',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'princess_and_dwarfs_rockways',
      Name: 'Princess and Dwarfs rockways',
      Description: '6*6 rockways, avalanche, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'loot_the_train',
      Name: 'Loot the Train',
      Description: '20 Lines, Bonus',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'deepsea_riches',
      Name: 'Deepsea Riches',
      Description: '20 Lines, Freespins',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'hydras_lair',
      Name: 'Hydras Lair',
      Description: '20 Lines, Freespins, wild feature',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'wildlife_riches',
      Name: 'Wildlife Riches',
      Description: '1024 ways, Bonus',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'the_candy_keno',
      Name: 'The Candy Keno',
      Description: '20/80 Balls, Extra balls',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'la_fiesta_de_muertos',
      Name: 'La Fiesta De Muertos',
      Description: '15 lines, respins, bonus',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'greedy_greenskins_rockways',
      Name: 'Greedy Greenskins Rockways',
      Description: '6*6 rockways, avalanche, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'cleopatras_gems_bingo',
      Name: "Cleopatra's Gems Bingo",
      Description: 'bingo',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'trump_card_queen',
      Name: 'Trump Card: Queen',
      Description: '6*3, 25 lines, bonus, freespins',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'fruit_machine_x25',
      Name: 'Fruit Machine x25',
      Description: '5*3, 20 Lines, freespins',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'easter_luck',
      Name: 'Easter Luck',
      Description: '3600 ways, respins',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'hook_up_fishing_wars',
      Name: 'Hook up! Fishing Wars',
      Description: '',
      SectionId: 'mascot',
      Type: 'casino',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'fruit_machine_megabonus',
      Name: 'Fruit Machine: Megabonus!',
      Description: '5*3, 10 lines, bonus',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'rocket_chimp_jackpot',
      Name: 'Rocket Chimp Jackpot!',
      Description: '5*3, 243 ways, freespins, jp',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'aloha_tiki_bar_dice',
      Name: 'Aloha Tiki Bar Dice',
      Description: '3600 ways, respins',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'dice_of_luxor',
      Name: 'Dice of Luxor',
      Description: '15 Lines, 2 way pay, Respin',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'dice_vegas',
      Name: 'Dice Vegas',
      Description: '10 Lines, 2 way pay, Respin',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'twin_dice_of_olympus',
      Name: 'Twin Dice of Olympus',
      Description: '1024 Way, Twin Reel',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'dice_disco_ms',
      Name: 'DICE DISCO: MEGA STACKS',
      Description: '20 lines, Twin Reel',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'ben_gunn_robinson',
      Name: 'Ben Gunn Robinson',
      Description: '10 Lines, Bonus',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'paper_lanterns_crash_game',
      Name: 'Paper Lanterns: Crash Game',
      Description: '5 Bets',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'wild_phoenix_rises',
      Name: 'Wild Phoenix Rises',
      Description: '25 Lines, free, rnb2',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'the_pendragon_legend',
      Name: 'the Pendragon Legend',
      Description: '20 Lines, Free, Risk-n-Buy',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'minotaurs_wilds',
      Name: 'Minotaurs Wilds',
      Description: '10 Lines, Free & Feature, rnb2',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'hello_win',
      Name: 'Hello Win',
      Description: '243 Ways, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'reveal_the_kraken',
      Name: 'Reveal the Kraken',
      Description: '5*4, 20 lines, bonus, freespins',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'zeus_the_thunderer_deluxe',
      Name: 'Zeus the Thunderer deluxe',
      Description: '20 Lines, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'book_of_anksunamun_rockways',
      Name: 'Book of Anksunamun Rockways',
      Description: '5*5 rockways, avalanche, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'christmas_infinite_gifts',
      Name: 'Christmas Infinite Gifts',
      Description: '5*4, 40 Lines, Free',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'dragons_lucky_25',
      Name: "Dragon's Lucky 25",
      Description: '5*3, 20 Lines, freespins, risk2.0',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'wild_wild_bet',
      Name: 'Wild Wild Bet',
      Description: '5 lines, Card-Slot, Poker',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'gryphons_castle_rush25',
      Name: 'Gryphons Castle Rush 25',
      Description: '20 Lines, Free, Rush25',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 're_kill_ultimate',
      Name: 'Re Kill Ultimate',
      Description: '5*4, 40 Lines, Free & Feature, WReels, Risk2.0, Buyin',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'crash_hamster_crash',
      Name: 'CRASH, HAMSTER, CRASH!',
      Description: 'crash',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'the_candy_slot_deluxe',
      Name: 'The Candy Slot Deluxe',
      Description: '6*5 rockways, avalanche, Free, features, rnb2',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'yukon_fever',
      Name: 'Yukon Fever',
      Description: '3*5, 5 lines, gamble',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'dreamshock_jackpot_x',
      Name: 'Dreamshock: Jackpot X',
      Description: '5*3, 243 ways, freespins, jp, riskwheel',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'mist',
      Name: 'Mist',
      Description: '10 Lines, 2 way pay, Respin',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'ice_number_one',
      Name: 'Ice Number One',
      Description: '3*4, 10 Lines, freespins, RnB2, side bet',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'hot_fruit_x15',
      Name: 'Hot Fruit x15',
      Description: '10 lines, multiplier, riskwheel',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'fabulous_farm_slot',
      Name: 'Fabulous Farm Slot',
      Description: '5*5, 3125 ways, Free, Bonus, Risk mines, buyin',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'big_win_x25',
      Name: 'Big Win x25',
      Description: '5 lines, multiplier, riskwheel',
      SectionId: 'mascot',
      Type: 'slots',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    },
    {
      Id: 'across_the_universe_keno',
      Name: 'Across the Universe Keno',
      Description: '20/80 Balls, Multipliers, Free',
      SectionId: 'mascot',
      Type: 'casino',
      Format: 'html',
      Settings: { CoinValue: 100, Denominations: [Array] }
    }
  ]

const fs = require('fs');
// List all the filenames before renaming 


// Rename the file 

 

for(let i = 0; i < dick.length; i++){
    fs.rename(
        __dirname + '/slots/' + dick[i].Name.replace(':','') + ".jpeg",
        __dirname + '/slots/' + dick[i].Id + ".jpeg",
        (e) => {
            console.log(e);

        });
}